
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techveo-web
  namespace: techveo
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techveo-management-api
  namespace: techveo
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techveo-management-worker
  namespace: techveo
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techveo-processing-worker
  namespace: techveo
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techveo-notification-worker
  namespace: techveo
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techveo-nginx
  namespace: techveo
spec:
  replicas: 1
