apiVersion: v1
kind: Secret
metadata:
  name: techveo-shared-secret
  namespace: techveo
  labels:
    app.kubernetes.io/name: techveo-shared-secret
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: techveo-system
type: Opaque
stringData:
  Authentication__Jwt__Key: ""
  EventBus__RabbitMQ__UserName: ""
  EventBus__RabbitMQ__Password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: techveo-management-secret
  namespace: techveo
  labels:
    app.kubernetes.io/name: techveo-management-secret
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: techveo-system
type: Opaque
stringData:
  ConnectionStrings__DataBaseConection: ""
  Authentication__ClientSecret: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: techveo-processing-secret
  namespace: techveo
  labels:
    app.kubernetes.io/name: techveo-processing-secret
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: techveo-system
type: Opaque
stringData:
  ConnectionStrings__DataBaseConection: ""
  Authentication__ClientSecret: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: techveo-notification-secret
  namespace: techveo
  labels:
    app.kubernetes.io/name: techveo-notification-secret
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: techveo-system
type: Opaque
stringData:
  ConnectionStrings__DataBaseConection: ""
  Authentication__ClientSecret: ""
